"""Public models for deterministic, inspectable Defined Quant operations."""

import sys
from pathlib import Path

# Hatch maps this readable source folder to ``defined_quant_protocol`` in a wheel. Its editable
# wheel adds the source folder itself to ``sys.path``. Extend this package path so the
# force-included bootstrap module continues to resolve live source modules during development.
for _entry in sys.path:
    _candidate = Path(_entry)
    if (
        _candidate.name == "protocol"
        and (_candidate / "canonical.py").is_file()
        and (_candidate / "operation.py").is_file()
    ):
        __path__.insert(0, str(_candidate))
        break

from .authorization import (  # noqa: E402
    AUTHORIZATION_BINDING_HASH_DOMAIN,
    MANUAL_APPROVAL_HASH_DOMAIN,
    VALIDATION_RECEIPT_HASH_DOMAIN,
    ApprovalRecord,
    AuthorizationBinding,
    AuthorizationErrorCode,
    AuthorizationFailure,
    AuthorizationOutcome,
    AuthorizationSuccess,
    ClarificationQuestion,
    PlanValidationOutcome,
    ValidationCheck,
    ValidationFailure,
    ValidationIssue,
    ValidationIssueCode,
    ValidationReceipt,
    approval_record_hash,
    authorization_binding_hash,
    managed_authorization_protocol_schema,
    validation_receipt_hash,
)
from .canonical import (  # noqa: E402
    CANONICALIZATION_ID,
    canonical_hash,
    canonical_hash_framing,
    canonical_json_bytes,
)
from .operation import (  # noqa: E402
    CallerProvenance,
    ComponentRef,
    FileDigest,
    InterpretationMethod,
    OperationError,
    OperationErrorCode,
    OperationFailure,
    OperationManifest,
    OperationProvenance,
    OperationRequest,
    OperationResult,
    OperationSuccess,
    ProvenanceStatus,
    RelativeMemberPath,
    RunnerIdentity,
    SourceKind,
    SvgArtifact,
    SvgArtifactRequest,
    VerificationStatus,
    operation_hash,
    operation_protocol_schema,
)
from .plan import (  # noqa: E402
    ANALYSIS_PLAN_HASH_DOMAIN,
    DATASET_BINDING_HASH_DOMAIN,
    AnalysisPlan,
    DatasetBinding,
    PlanStep,
    QuestionVerificationStatus,
    ResolvedQuestion,
    analysis_plan_hash,
    dataset_binding_hash,
)
from .policy import (  # noqa: E402
    EXECUTION_POLICY_HASH_DOMAIN,
    ComponentLifecycle,
    ExecutionPolicy,
    InputRequirement,
    ManagedComponentRule,
    RequirementFailureCode,
    execution_policy_hash,
)
from .ports import (  # noqa: E402
    PORT_SCHEMA_KEY,
    IncompatiblePortsError,
    PortCardinality,
    PortCompatibility,
    PortConcept,
    PortConvention,
    PortDifference,
    PortDimension,
    PortDirection,
    PortFrequency,
    PortOrdering,
    PortProvenanceRequirement,
    PortShape,
    PortUnit,
    PortValue,
    SemanticPort,
    SemanticPortError,
    compare_semantic_ports,
    extract_semantic_port,
    require_compatible_ports,
    semantic_port_metadata,
)
from .version import (  # noqa: E402
    PROTOCOL_VERSION,
    SUPPORTED_PROTOCOL_VERSIONS,
    ProtocolVersion,
)

__version__ = PROTOCOL_VERSION

__all__ = [
    "PROTOCOL_VERSION",
    "SUPPORTED_PROTOCOL_VERSIONS",
    "ProtocolVersion",
    "CANONICALIZATION_ID",
    "ANALYSIS_PLAN_HASH_DOMAIN",
    "AnalysisPlan",
    "ApprovalRecord",
    "AuthorizationBinding",
    "AUTHORIZATION_BINDING_HASH_DOMAIN",
    "AuthorizationErrorCode",
    "AuthorizationFailure",
    "AuthorizationOutcome",
    "AuthorizationSuccess",
    "CallerProvenance",
    "ComponentRef",
    "ComponentLifecycle",
    "ClarificationQuestion",
    "DatasetBinding",
    "DATASET_BINDING_HASH_DOMAIN",
    "EXECUTION_POLICY_HASH_DOMAIN",
    "ExecutionPolicy",
    "FileDigest",
    "InterpretationMethod",
    "OperationError",
    "OperationErrorCode",
    "OperationFailure",
    "OperationManifest",
    "OperationProvenance",
    "OperationRequest",
    "OperationResult",
    "OperationSuccess",
    "PORT_SCHEMA_KEY",
    "PlanStep",
    "PlanValidationOutcome",
    "PortCardinality",
    "PortCompatibility",
    "PortConcept",
    "PortConvention",
    "PortDifference",
    "PortDimension",
    "PortDirection",
    "PortFrequency",
    "PortOrdering",
    "PortProvenanceRequirement",
    "PortShape",
    "PortUnit",
    "PortValue",
    "ProvenanceStatus",
    "QuestionVerificationStatus",
    "RelativeMemberPath",
    "RunnerIdentity",
    "ResolvedQuestion",
    "RequirementFailureCode",
    "SourceKind",
    "SemanticPort",
    "SemanticPortError",
    "SvgArtifact",
    "SvgArtifactRequest",
    "VerificationStatus",
    "ValidationCheck",
    "ValidationFailure",
    "ValidationIssue",
    "ValidationIssueCode",
    "ValidationReceipt",
    "VALIDATION_RECEIPT_HASH_DOMAIN",
    "InputRequirement",
    "IncompatiblePortsError",
    "ManagedComponentRule",
    "MANUAL_APPROVAL_HASH_DOMAIN",
    "analysis_plan_hash",
    "approval_record_hash",
    "authorization_binding_hash",
    "canonical_hash",
    "canonical_hash_framing",
    "canonical_json_bytes",
    "compare_semantic_ports",
    "dataset_binding_hash",
    "execution_policy_hash",
    "extract_semantic_port",
    "managed_authorization_protocol_schema",
    "operation_hash",
    "operation_protocol_schema",
    "require_compatible_ports",
    "semantic_port_metadata",
    "validation_receipt_hash",
]

del _candidate, _entry
