"""Compatibility imports for the independently versioned operation protocol."""

from defined_quant_protocol import (
    CANONICALIZATION_ID,
    PROTOCOL_VERSION,
    CallerProvenance,
    ComponentRef,
    FileDigest,
    InterpretationMethod,
    OperationError,
    OperationErrorCode,
    OperationFailure,
    OperationManifest,
    OperationProvenance,
    OperationRequest,
    OperationResult,
    OperationSuccess,
    ProvenanceStatus,
    RelativeMemberPath,
    RunnerIdentity,
    SourceKind,
    SvgArtifact,
    SvgArtifactRequest,
    VerificationStatus,
    canonical_hash,
    canonical_json_bytes,
    operation_hash,
    operation_protocol_schema,
)
from defined_quant_protocol.operation import portable_member_key

__all__ = [
    "CANONICALIZATION_ID",
    "PROTOCOL_VERSION",
    "CallerProvenance",
    "ComponentRef",
    "FileDigest",
    "InterpretationMethod",
    "OperationError",
    "OperationErrorCode",
    "OperationFailure",
    "OperationManifest",
    "OperationProvenance",
    "OperationRequest",
    "OperationResult",
    "OperationSuccess",
    "ProvenanceStatus",
    "RelativeMemberPath",
    "RunnerIdentity",
    "SourceKind",
    "SvgArtifact",
    "SvgArtifactRequest",
    "VerificationStatus",
    "canonical_hash",
    "canonical_json_bytes",
    "operation_hash",
    "operation_protocol_schema",
    "portable_member_key",
]
